services:
  tradeflow:
    image: tradeflow:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: tradeflow

    restart: unless-stopped

    env_file:
      - .env.production

    networks:
      - proxy
      - backend

  migrate:
  build:
    context: .
    dockerfile: Dockerfile.migrate

  env_file:
    - .env.production

  command: ["npm", "run", "db:migrate"]

  restart: "no"

  networks:
    - backend

networks:
  proxy:
    external: true

  backend: